shinyUI(
  navbarPage("Campanhas de Trânsito",
    tabPanel("Como Utilizar?",
               p("No menu, temos 3 campanhas de trânsito e o comparativo geral, para começar, clique em um dos itens e escolha o subitem desejado.",
                        br(),
                        "Esse subitem pode ser o mapa interativo (se clicar em uma campanha de trânsito), gráficos ou árvore de decisão.",
                        br(),
                        br(),
                        "Caso você tenha escolhido a opção MAPA, você deverá clicar no ícone que se encontra dentro de um quadrado branco e tem um símbolo de 3 camadas, no canto superior direito da tela e marcar na caixa o(s) campo(s) que você deseja ver no mapa.",
                        br(),
                        br(),
                        br(),br(),br(),
                        "Dúvidas ou sugestões, entre em contato através do email:",br(),
                        "caraujo@inf.ufsm.br"), style ="font-family:'times'; font-size: 200%"),
    navbarMenu("Maio Amarelo",
        tabPanel("Mapa",leafletOutput("map",height=800)),
        tabPanel("Gráfico de Causas de Acidentes", highchartOutput("PizzaCausaMaio")),
        tabPanel("Gráfico de Acidentes por BR", highchartOutput("BarraBRMaio")),
        tabPanel("Gráfico de Acidentes por Dia", highchartOutput("BarraDiaMaio")),
        tabPanel("Árvore de Decisão - Probabilidade de Ilesos", plotOutput("ArvoreMaio1", height = 600))),
    navbarMenu("Se beber não dirija",
        tabPanel("Mapa", leafletOutput("mapas", height = 800)),
        tabPanel("Gráfico do Sexo dos Causadores de Acidente após Ingestão de Álcool nos Anos de 2017, 2018 e 2019",highchartOutput("PizzaSexoLeiSeca")),
        tabPanel("Gráfico Comparativo de Acidentes por ano",uiOutput("BarraAcidentesAnoLeiSeca")),
        tabPanel("Gráfico de Acidentes por Dia", highchartOutput("BarraDiaLeiSeca")),
        tabPanel("Árvore de Decisão - Probabilidade de Ilesos", plotOutput("ArvoreLeiSeca1", height = 600))),
    navbarMenu("Época de Veraneio",
        tabPanel("Mapa",leafletOutput("mapaVerao", height = 800)),
        tabPanel("Gráfico de Causas de Acidentes", highchartOutput("PizzaCausaVeraneio")),
        tabPanel("Gráfico de Acidentes por BR", highchartOutput("BarraBRVeraneio")),
        tabPanel("Gráfico de Acidentes por Dia", highchartOutput("BarraDiaVeraneio")),
        tabPanel("Árvore de Decisão Ilesos - Probabilidade de Ilesos", plotOutput("ArvoreVeraneio", height = 600))),
    navbarMenu("Comparativos Gerais",
        tabPanel("Gráfico de Acidentes Mensais(2017-2018)", highchartOutput("BarraMesTotal")),
        tabPanel("Gráfico de Acidentes Dias Semanais(2017-2018)", highchartOutput("BarraDiaTotal"),uiOutput("ListaDias")),
        tabPanel("Gráfico de Acidentes por Causa(2017-2018)",highchartOutput("PizzaCausaTotal"), uiOutput("PizzaCausas")),
        tabPanel("Comparativo dos Algoritmos - Naive Bayes e Árvore de Decisão", p("Foi elaborada uma situação hipotética de um(a) condutor(a) que viaje em um sábado durante a época de veraneio.",br(),style ="font-family:'times'; font-size: 200%",
                                                                                   p("Naive Bayes fez a predição de 68% e a Árvore de decisão 60%, conforme ilustração abaixo:",br(),style ="font-family:'times'; font-size: 200%"),plotOutput("Comparativo", height = 600))))
    )
)